name: syntax
on: push
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - run: echo Badoi Iulia-Bianca
    - run: |
        if [ $("python add 1 2") != "3" ] echo 1 fi
